spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: ${profile:dev}
    gateway:
      routes:
        - id: apimovies
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
        - id: apicatalog
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog/**
